#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/db_flow_chart?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=nopassword
#spring.datasource.data="data.sql

server:
  port: 8080
spring:
  application:
    name: knowledge_graph.flow_chart
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    data: classpath:data.sql
    url: jdbc:mysql://localhost:3306/db_flow_chart?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    data-username: root
    data-password: nopassword